### PR TITLE
Fix desorption checking logic in `Analysis.Diatomic`

### LINKED ISSUE #367: 🧪 Missing index rounding in Analysis.Diatomic.get_desorption_angle
CI tests for desorption analysis currently fail due to a Float64 index being produced, which should be rounded to an Int.

### PR DESCRIPTION
**Pull request by Alexsp32**
`Analysis.Diatomic.surface_distance_condition` was incorrectly calling `Analysis.Diatomic.surface_normal_height` without a `surface_normal` argument, which was included in a `symdiff` call to find all non-diatomic atom indices instead. 

This resulted in these atom indices being returned as `Float64`s, which caused indexing to fail down the line. 

Fixes #367.

### CODE REVIEW

File: src/structure.jl [hunk 1]
```diff
@@ -152,32 +152,32 @@ function minimum_distance_translation(config::AbstractVector, ind1::Int, ind2::I
     return minimum_distance_translation(get_positions(config),ind1,ind2,simulation.cell;cutoff=cutoff)
 end
 
-function pbc_distance(config::Matrix, ind1, ind2, sim::AbstractSimulation; args...)
+function pbc_distance(config::Matrix, ind1::int_or_index, ind2::int_or_index, sim::AbstractSimulation; args...)
```
Comment (reinimaurer1) [inline src/structure.jl:155]: I am not sure I link this `int_or_index`

**Review by reinimaurer1 — APPROVED** [review]
looks good
